apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterWide: true
  replicas: 1
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
